services:
  burndown:
    build: ./scripts/burndown
    volumes:
      - ${BURNDOWN_DATA:-./burndown}:/data
    environment:
      INPUT: /data/data.csv
      OUTPUT: /data/plot.svg
      GH_TOKEN: ${GH_TOKEN:-lol}

  # the .env should be created manually by each of you in backend/server_db/.env
  # command to run just postgres: docker-compose --env-file backend/server_db/.env up -d postgres 
  postgres: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backend/server_db/sql_scripts:/docker-entrypoint-initdb.d
      - ./backend/server_db/data:/var/lib/postgresql/data
      - ./backend/server_db/migrations:/migrations 
    network_mode: host 
