services:
  burndown:
    build: ./burndown
    volumes:
      - ${BURNDOWN_DATA:-./burndown}:/data
    environment:
      INPUT: /data/data.csv
      OUTPUT: /data/plot.svg
      GH_TOKEN: ${GH_TOKEN:-lol}
