name: "Continuous delivery"
on:
  workflow_dispatch:
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: Copy everything to the server
        run: rsync -urltv --delete -e ssh ./ ${{secrets.SSH_HOST}}:studybuds
